version: '3.4'

services:
  interactions-cron-job:
    container_name: interactions-cron-job
    image: node
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "7070:7070"
    command: /bin/bash -c 'yarn; yarn start;'
    networks:
      - interactions-cron-job

networks:
  interactions-cron-job: